### ISSUE TITLE
Redirects capped at 12 entries

### ISSUE THREAD

**Issue by Salsa85** [justkidding96/statamic-aardvark-seo#157]
Adding manual redirects won't go past 12 entries. 

I have also tried to add them manually, but with no avail. It remains capped at 12 entries.

Am i missing something?

Additional information: 

Multisite: Yes

The manual.yaml contents:

```
default:
  -
    source_url: /tuinkussens
    target_url: tuinkussens-op-maat
    status_code: '301'
    is_active: true
    id: a2b3e483-10f7-45f9-8536-02b7130afbe9
  -
    source_url: /loungekussens
    target_url: loungekussens-op-maat
    status_code: '301'
    is_active: true
    id: f9fcc2ec-b87b-4cfe-9a91-8244cb190511
  -
    source_url: /tuinbankkussens-op-maat
    target_url: tuinkussens-op-maat
    status_code: '301'
    is_active: true
    id: 1125497b-ac50-400b-9b2f-48414f59471c
  -
    source_url: /tuinbankkussens
    target_url: tuinkussens-op-maat
    status_code: '301'
    is_active: true
    id: 3fec7459-b6be-4d74-8e4f-149c48936b76
  -
    source_url: /start-met-ontwerpen/afwerkingen
    target_url: kussens-op-maat/afwerkingen
    status_code: '301'
    is_active: true
    id: 942d946f-a760-4440-beab-cd7f4b8a20b3
  -
    source_url: /privacy-verklaring
    target_url: privacy-beleid
    status_code: '301'
    is_active: true
    id: 57d67115-1d20-49d8-bb77-609fd35f42a6
  -
    source_url: /tuinmeubelkussens
    target_url: tuinkussens-op-maat
    status_code: '301'
    is_active: true
    id: 7ca69fd9-5e5f-406e-8e77-cc54b2f889f2
  -
    source_url: /werking
    target_url: hoe-werkt-het
    status_code: '301'
    is_active: true
    id: d293f110-1cf5-4de4-9b06-958aafc9031a
  -
    source_url: /maatberekening
    target_url: meethulp
    status_code: '301'
    is_active: true
    id: 9330c11d-94b8-488c-abc6-ea375437403f
  -
    source_url: /ligbedkussen-op-maat
    target_url: ligbedkussens-op-maat
    status_code: '301'
    is_active: true
    id: e54e69bc-c539-460d-8d27-40e9cd0a1dd9
  -
    source_url: /tuinkussens-op-maat-laten-maken
    target_url: tuinkussens-op-maat
    status_code: '301'
    is_active: true
    id: 96e9a7a7-aa9c-447a-9e9c-42ce6837bc51
  -
    source_url: /ontwerp-tools
    target_url: start-met-ontwerpen
    status_code: '301'
    is_active: true
    id: bc86f58c-212a-497f-992a-d99e2950b02e
```

Screenshot: 

![Scherm­afbeelding 2023-04-12 om 22 34 45](https://user-images.githubusercontent.com/42177921/231578291-c32e99db-8712-4bbb-8bfd-168bf1251c46.png)
